"""add qa_logs table

Revision ID: 46105d6796f1
Revises: c0892f4993d3
Create Date: 2025-10-02 16:17:28.523100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46105d6796f1'
down_revision = 'c0892f4993d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_logs', schema='app')
    # ### end Alembic commands ###
