"""update qa_logs with correct columns

Revision ID: f317549f7a90
Revises: 46105d6796f1
Create Date: 2025-10-02 17:21:54.155422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f317549f7a90'
down_revision = '46105d6796f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_logs', sa.Column('agent_id', sa.String(length=100), nullable=True), schema='app')
    op.add_column('qa_logs', sa.Column('model', sa.String(length=100), nullable=True), schema='app')
    op.add_column('qa_logs', sa.Column('device', sa.String(length=50), nullable=True), schema='app')
    op.add_column('qa_logs', sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='app')
    op.add_column('qa_logs', sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='app')
    op.drop_column('qa_logs', 'extra_data', schema='app')
    op.drop_column('qa_logs', 'question', schema='app')
    op.drop_column('qa_logs', 'answer', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_logs', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True), schema='app')
    op.add_column('qa_logs', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False), schema='app')
    op.add_column('qa_logs', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='app')
    op.drop_column('qa_logs', 'response_json', schema='app')
    op.drop_column('qa_logs', 'request_json', schema='app')
    op.drop_column('qa_logs', 'device', schema='app')
    op.drop_column('qa_logs', 'model', schema='app')
    op.drop_column('qa_logs', 'agent_id', schema='app')
    # ### end Alembic commands ###
