name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Validate Docker Compose
      run: docker compose config

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Start services
      run: |
        docker compose up -d
        sleep 30
    - name: Test endpoints
      run: |
        curl -f http://localhost:8000/health
        curl -f http://localhost:8001/health
    - name: Cleanup
      run: docker compose down -v
